version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${password}
      POSTGRES_USER: ${user}
    env_file:
      - .env


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
